apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-deployment
  name: web-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-deployment
    spec:
      containers:
      - image: busybox:latest
        name: busybox
        resources: {}
status: {}
